#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo > ~/.zshrc

echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' > ~/.zshrc

source ~/.zshrc
